import * as THREE from "three";
import { createGameScene } from "./scene/world.js";
import { setupNativeBridge } from "./native/capacitor-bridge.js";
import { mountGameShell } from "./ui/game-shell.js";
import { mountVisionUpgrade } from "./ui/vision-upgrade.js";
import { mountDailyQuests } from "./ui/daily-quests.js";
import { mountBrawlRestyle } from "./ui/brawl-restyle.js";
import { mountBrawlCleanup } from "./ui/brawl-cleanup.js";
import { mountFreshLearningTheme } from "./ui/fresh-learning-theme.js";
import { mountMusicLearningOverlay } from "./ui/music-learning-overlay.js";
import { mountRhythmBattle } from "./ui/rhythm-battle.js";
import { mountRhythmArena3D } from "./scene/rhythm-arena-3d.js";

const runtime = createGameScene({ THREE });
setupNativeBridge(runtime);
mountGameShell(runtime);
mountVisionUpgrade(runtime);
mountDailyQuests(runtime);
mountBrawlRestyle(runtime);
mountBrawlCleanup();
mountFreshLearningTheme();
mountRhythmArena3D();
mountRhythmBattle();
mountMusicLearningOverlay();
